library(data.table)
library(ggplot2)
library(scales)
library(reshape2)
library(gridExtra)

raw <- fread(
    "lifespan-by-id-with-type.csv",
    header=T,
    na.strings="\\N",
    colClasses=c("character", "character", "numeric", "numeric")
)
raw <- raw[between(formation, 2000, 2014) & (between(dissolution, 2000, 2015) | is.na(dissolution))]

## This is a manual cleaning step to remove duplicate rows generated by changes in entity type
fixes <- raw[id_bus %in% c("1122906","1108868","1097607","1088811","1037395","0844504","0779572") & type == "LLC",]
fixes[, type := "BEN"]

raw <- raw[(!id_bus %in% c("1122906","1108868","1097607","1088811","1037395","0844504","0779572"))]
raw <- rbind(raw, fixes)

fixes <- raw[id_bus == "0691131" & type == "LLC"]
fixes[, type := "LLC"]
raw <- raw[id_bus != "0691131"]
raw <- rbind(raw, fixes)
## end manual fix


raw[
    ,
    Type := switch(
        type,
        CORP = "Corporation",
        LLC = "LLC",
        "Other"
    ),
    by = type
][, `:=`(
    type = NULL,
    Cohort = formation,
    formation = NULL
)]


cohorts <- c(2000, 2008)

denominators <- raw[
    ,
    list(Total = .N),
    by = list(Cohort, Type)
]

data <- raw[
    Cohort %in% cohorts
    & !is.na(dissolution),
    .N,
    by = list(Cohort, Type, dissolution)][order(dissolution)
]

setkey(denominators, Cohort, Type)
setkey(data, Cohort, Type)
data <- denominators[data]

data[, row := 1:.N]

data[
    ,
    agg := sum(data[Cohort == .SD$Cohort & Type == .SD$Type & dissolution < .SD$dissolution, N]),
    by = row
]

data[, `:=`(
    Value = (100 * (Total - agg) / Total),
    N = NULL,
    Total = NULL,
    Year = dissolution,
    dissolution = NULL,
    row = NULL,
    agg = NULL
)]

write.table(
    data,
    "survival-rates-by-cohort.csv",
    sep = ",",
    row.names = F
)
